language: python
python: 
 - "3.6"
 - "nightly"
install:
 - "pip install pytest"
 - "pip install -r requirements.txt"
script: python -m pytest tests/

language: node_js
node_js: 
 - "8.2.1"
install:
 - npm install newman
before_script:
 - node --version 
 - npm --version 
 - node_modules/.bin/newman --version 
 - python3 --version 
 - python3 app.py
script:
 - node_modules/.bin/newman run ./usr_.postman_collection.json -e ./usr_.postman_environment.json 